// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: User.proto

package pl.marchuck.protobuffersexample.model;

public final class UserProtos {
  private UserProtos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface UserOrBuilder extends
      // @@protoc_insertion_point(interface_extends:pl.marchuck.protobuffersexample.User)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required int32 id = 1;</code>
     */
    boolean hasId();
    /**
     * <code>required int32 id = 1;</code>
     */
    int getId();

    /**
     * <code>required string firstName = 2;</code>
     */
    boolean hasFirstName();
    /**
     * <code>required string firstName = 2;</code>
     */
    java.lang.String getFirstName();
    /**
     * <code>required string firstName = 2;</code>
     */
    com.google.protobuf.ByteString
        getFirstNameBytes();

    /**
     * <code>required string lastName = 3;</code>
     */
    boolean hasLastName();
    /**
     * <code>required string lastName = 3;</code>
     */
    java.lang.String getLastName();
    /**
     * <code>required string lastName = 3;</code>
     */
    com.google.protobuf.ByteString
        getLastNameBytes();

    /**
     * <code>optional int32 level = 4 [default = 0];</code>
     */
    boolean hasLevel();
    /**
     * <code>optional int32 level = 4 [default = 0];</code>
     */
    int getLevel();

    /**
     * <code>repeated .pl.marchuck.protobuffersexample.User.Monster monsters = 5;</code>
     */
    java.util.List<pl.marchuck.protobuffersexample.model.UserProtos.User.Monster> 
        getMonstersList();
    /**
     * <code>repeated .pl.marchuck.protobuffersexample.User.Monster monsters = 5;</code>
     */
    pl.marchuck.protobuffersexample.model.UserProtos.User.Monster getMonsters(int index);
    /**
     * <code>repeated .pl.marchuck.protobuffersexample.User.Monster monsters = 5;</code>
     */
    int getMonstersCount();
    /**
     * <code>repeated .pl.marchuck.protobuffersexample.User.Monster monsters = 5;</code>
     */
    java.util.List<? extends pl.marchuck.protobuffersexample.model.UserProtos.User.MonsterOrBuilder> 
        getMonstersOrBuilderList();
    /**
     * <code>repeated .pl.marchuck.protobuffersexample.User.Monster monsters = 5;</code>
     */
    pl.marchuck.protobuffersexample.model.UserProtos.User.MonsterOrBuilder getMonstersOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code pl.marchuck.protobuffersexample.User}
   */
  public  static final class User extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:pl.marchuck.protobuffersexample.User)
      UserOrBuilder {
    // Use User.newBuilder() to construct.
    private User(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private User() {
      id_ = 0;
      firstName_ = "";
      lastName_ = "";
      level_ = 0;
      monsters_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private User(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              id_ = input.readInt32();
              break;
            }
            case 18: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000002;
              firstName_ = bs;
              break;
            }
            case 26: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000004;
              lastName_ = bs;
              break;
            }
            case 32: {
              bitField0_ |= 0x00000008;
              level_ = input.readInt32();
              break;
            }
            case 42: {
              if (!((mutable_bitField0_ & 0x00000010) == 0x00000010)) {
                monsters_ = new java.util.ArrayList<pl.marchuck.protobuffersexample.model.UserProtos.User.Monster>();
                mutable_bitField0_ |= 0x00000010;
              }
              monsters_.add(
                  input.readMessage(pl.marchuck.protobuffersexample.model.UserProtos.User.Monster.PARSER, extensionRegistry));
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000010) == 0x00000010)) {
          monsters_ = java.util.Collections.unmodifiableList(monsters_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return pl.marchuck.protobuffersexample.model.UserProtos.internal_static_pl_marchuck_protobuffersexample_User_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return pl.marchuck.protobuffersexample.model.UserProtos.internal_static_pl_marchuck_protobuffersexample_User_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              pl.marchuck.protobuffersexample.model.UserProtos.User.class, pl.marchuck.protobuffersexample.model.UserProtos.User.Builder.class);
    }

    public interface MonsterOrBuilder extends
        // @@protoc_insertion_point(interface_extends:pl.marchuck.protobuffersexample.User.Monster)
        com.google.protobuf.MessageOrBuilder {

      /**
       * <code>required int32 id = 1;</code>
       */
      boolean hasId();
      /**
       * <code>required int32 id = 1;</code>
       */
      int getId();

      /**
       * <code>required string name = 2;</code>
       */
      boolean hasName();
      /**
       * <code>required string name = 2;</code>
       */
      java.lang.String getName();
      /**
       * <code>required string name = 2;</code>
       */
      com.google.protobuf.ByteString
          getNameBytes();

      /**
       * <code>optional string type = 3 [default = "n/a"];</code>
       */
      boolean hasType();
      /**
       * <code>optional string type = 3 [default = "n/a"];</code>
       */
      java.lang.String getType();
      /**
       * <code>optional string type = 3 [default = "n/a"];</code>
       */
      com.google.protobuf.ByteString
          getTypeBytes();
    }
    /**
     * Protobuf type {@code pl.marchuck.protobuffersexample.User.Monster}
     */
    public  static final class Monster extends
        com.google.protobuf.GeneratedMessageV3 implements
        // @@protoc_insertion_point(message_implements:pl.marchuck.protobuffersexample.User.Monster)
        MonsterOrBuilder {
      // Use Monster.newBuilder() to construct.
      private Monster(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
        super(builder);
      }
      private Monster() {
        id_ = 0;
        name_ = "";
        type_ = "n/a";
      }

      @java.lang.Override
      public final com.google.protobuf.UnknownFieldSet
      getUnknownFields() {
        return this.unknownFields;
      }
      private Monster(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        this();
        int mutable_bitField0_ = 0;
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
            com.google.protobuf.UnknownFieldSet.newBuilder();
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              default: {
                if (!parseUnknownField(input, unknownFields,
                                       extensionRegistry, tag)) {
                  done = true;
                }
                break;
              }
              case 8: {
                bitField0_ |= 0x00000001;
                id_ = input.readInt32();
                break;
              }
              case 18: {
                com.google.protobuf.ByteString bs = input.readBytes();
                bitField0_ |= 0x00000002;
                name_ = bs;
                break;
              }
              case 26: {
                com.google.protobuf.ByteString bs = input.readBytes();
                bitField0_ |= 0x00000004;
                type_ = bs;
                break;
              }
            }
          }
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(this);
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(
              e).setUnfinishedMessage(this);
        } finally {
          this.unknownFields = unknownFields.build();
          makeExtensionsImmutable();
        }
      }
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return pl.marchuck.protobuffersexample.model.UserProtos.internal_static_pl_marchuck_protobuffersexample_User_Monster_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return pl.marchuck.protobuffersexample.model.UserProtos.internal_static_pl_marchuck_protobuffersexample_User_Monster_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                pl.marchuck.protobuffersexample.model.UserProtos.User.Monster.class, pl.marchuck.protobuffersexample.model.UserProtos.User.Monster.Builder.class);
      }

      private int bitField0_;
      public static final int ID_FIELD_NUMBER = 1;
      private int id_;
      /**
       * <code>required int32 id = 1;</code>
       */
      public boolean hasId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required int32 id = 1;</code>
       */
      public int getId() {
        return id_;
      }

      public static final int NAME_FIELD_NUMBER = 2;
      private volatile java.lang.Object name_;
      /**
       * <code>required string name = 2;</code>
       */
      public boolean hasName() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required string name = 2;</code>
       */
      public java.lang.String getName() {
        java.lang.Object ref = name_;
        if (ref instanceof java.lang.String) {
          return (java.lang.String) ref;
        } else {
          com.google.protobuf.ByteString bs = 
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            name_ = s;
          }
          return s;
        }
      }
      /**
       * <code>required string name = 2;</code>
       */
      public com.google.protobuf.ByteString
          getNameBytes() {
        java.lang.Object ref = name_;
        if (ref instanceof java.lang.String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }

      public static final int TYPE_FIELD_NUMBER = 3;
      private volatile java.lang.Object type_;
      /**
       * <code>optional string type = 3 [default = "n/a"];</code>
       */
      public boolean hasType() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional string type = 3 [default = "n/a"];</code>
       */
      public java.lang.String getType() {
        java.lang.Object ref = type_;
        if (ref instanceof java.lang.String) {
          return (java.lang.String) ref;
        } else {
          com.google.protobuf.ByteString bs = 
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            type_ = s;
          }
          return s;
        }
      }
      /**
       * <code>optional string type = 3 [default = "n/a"];</code>
       */
      public com.google.protobuf.ByteString
          getTypeBytes() {
        java.lang.Object ref = type_;
        if (ref instanceof java.lang.String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          type_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }

      private byte memoizedIsInitialized = -1;
      public final boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized == 1) return true;
        if (isInitialized == 0) return false;

        if (!hasId()) {
          memoizedIsInitialized = 0;
          return false;
        }
        if (!hasName()) {
          memoizedIsInitialized = 0;
          return false;
        }
        memoizedIsInitialized = 1;
        return true;
      }

      public void writeTo(com.google.protobuf.CodedOutputStream output)
                          throws java.io.IOException {
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          output.writeInt32(1, id_);
        }
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          com.google.protobuf.GeneratedMessageV3.writeString(output, 2, name_);
        }
        if (((bitField0_ & 0x00000004) == 0x00000004)) {
          com.google.protobuf.GeneratedMessageV3.writeString(output, 3, type_);
        }
        unknownFields.writeTo(output);
      }

      public int getSerializedSize() {
        int size = memoizedSize;
        if (size != -1) return size;

        size = 0;
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          size += com.google.protobuf.CodedOutputStream
            .computeInt32Size(1, id_);
        }
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, name_);
        }
        if (((bitField0_ & 0x00000004) == 0x00000004)) {
          size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, type_);
        }
        size += unknownFields.getSerializedSize();
        memoizedSize = size;
        return size;
      }

      private static final long serialVersionUID = 0L;
      @java.lang.Override
      public boolean equals(final java.lang.Object obj) {
        if (obj == this) {
         return true;
        }
        if (!(obj instanceof pl.marchuck.protobuffersexample.model.UserProtos.User.Monster)) {
          return super.equals(obj);
        }
        pl.marchuck.protobuffersexample.model.UserProtos.User.Monster other = (pl.marchuck.protobuffersexample.model.UserProtos.User.Monster) obj;

        boolean result = true;
        result = result && (hasId() == other.hasId());
        if (hasId()) {
          result = result && (getId()
              == other.getId());
        }
        result = result && (hasName() == other.hasName());
        if (hasName()) {
          result = result && getName()
              .equals(other.getName());
        }
        result = result && (hasType() == other.hasType());
        if (hasType()) {
          result = result && getType()
              .equals(other.getType());
        }
        result = result && unknownFields.equals(other.unknownFields);
        return result;
      }

      @java.lang.Override
      public int hashCode() {
        if (memoizedHashCode != 0) {
          return memoizedHashCode;
        }
        int hash = 41;
        hash = (19 * hash) + getDescriptorForType().hashCode();
        if (hasId()) {
          hash = (37 * hash) + ID_FIELD_NUMBER;
          hash = (53 * hash) + getId();
        }
        if (hasName()) {
          hash = (37 * hash) + NAME_FIELD_NUMBER;
          hash = (53 * hash) + getName().hashCode();
        }
        if (hasType()) {
          hash = (37 * hash) + TYPE_FIELD_NUMBER;
          hash = (53 * hash) + getType().hashCode();
        }
        hash = (29 * hash) + unknownFields.hashCode();
        memoizedHashCode = hash;
        return hash;
      }

      public static pl.marchuck.protobuffersexample.model.UserProtos.User.Monster parseFrom(
          com.google.protobuf.ByteString data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static pl.marchuck.protobuffersexample.model.UserProtos.User.Monster parseFrom(
          com.google.protobuf.ByteString data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static pl.marchuck.protobuffersexample.model.UserProtos.User.Monster parseFrom(byte[] data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static pl.marchuck.protobuffersexample.model.UserProtos.User.Monster parseFrom(
          byte[] data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static pl.marchuck.protobuffersexample.model.UserProtos.User.Monster parseFrom(java.io.InputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input);
      }
      public static pl.marchuck.protobuffersexample.model.UserProtos.User.Monster parseFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input, extensionRegistry);
      }
      public static pl.marchuck.protobuffersexample.model.UserProtos.User.Monster parseDelimitedFrom(java.io.InputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseDelimitedWithIOException(PARSER, input);
      }
      public static pl.marchuck.protobuffersexample.model.UserProtos.User.Monster parseDelimitedFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
      }
      public static pl.marchuck.protobuffersexample.model.UserProtos.User.Monster parseFrom(
          com.google.protobuf.CodedInputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input);
      }
      public static pl.marchuck.protobuffersexample.model.UserProtos.User.Monster parseFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input, extensionRegistry);
      }

      public Builder newBuilderForType() { return newBuilder(); }
      public static Builder newBuilder() {
        return DEFAULT_INSTANCE.toBuilder();
      }
      public static Builder newBuilder(pl.marchuck.protobuffersexample.model.UserProtos.User.Monster prototype) {
        return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
      }
      public Builder toBuilder() {
        return this == DEFAULT_INSTANCE
            ? new Builder() : new Builder().mergeFrom(this);
      }

      @java.lang.Override
      protected Builder newBuilderForType(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        Builder builder = new Builder(parent);
        return builder;
      }
      /**
       * Protobuf type {@code pl.marchuck.protobuffersexample.User.Monster}
       */
      public static final class Builder extends
          com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
          // @@protoc_insertion_point(builder_implements:pl.marchuck.protobuffersexample.User.Monster)
          pl.marchuck.protobuffersexample.model.UserProtos.User.MonsterOrBuilder {
        public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
          return pl.marchuck.protobuffersexample.model.UserProtos.internal_static_pl_marchuck_protobuffersexample_User_Monster_descriptor;
        }

        protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internalGetFieldAccessorTable() {
          return pl.marchuck.protobuffersexample.model.UserProtos.internal_static_pl_marchuck_protobuffersexample_User_Monster_fieldAccessorTable
              .ensureFieldAccessorsInitialized(
                  pl.marchuck.protobuffersexample.model.UserProtos.User.Monster.class, pl.marchuck.protobuffersexample.model.UserProtos.User.Monster.Builder.class);
        }

        // Construct using pl.marchuck.protobuffersexample.model.UserProtos.User.Monster.newBuilder()
        private Builder() {
          maybeForceBuilderInitialization();
        }

        private Builder(
            com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
          super(parent);
          maybeForceBuilderInitialization();
        }
        private void maybeForceBuilderInitialization() {
          if (com.google.protobuf.GeneratedMessageV3
                  .alwaysUseFieldBuilders) {
          }
        }
        public Builder clear() {
          super.clear();
          id_ = 0;
          bitField0_ = (bitField0_ & ~0x00000001);
          name_ = "";
          bitField0_ = (bitField0_ & ~0x00000002);
          type_ = "n/a";
          bitField0_ = (bitField0_ & ~0x00000004);
          return this;
        }

        public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
          return pl.marchuck.protobuffersexample.model.UserProtos.internal_static_pl_marchuck_protobuffersexample_User_Monster_descriptor;
        }

        public pl.marchuck.protobuffersexample.model.UserProtos.User.Monster getDefaultInstanceForType() {
          return pl.marchuck.protobuffersexample.model.UserProtos.User.Monster.getDefaultInstance();
        }

        public pl.marchuck.protobuffersexample.model.UserProtos.User.Monster build() {
          pl.marchuck.protobuffersexample.model.UserProtos.User.Monster result = buildPartial();
          if (!result.isInitialized()) {
            throw newUninitializedMessageException(result);
          }
          return result;
        }

        public pl.marchuck.protobuffersexample.model.UserProtos.User.Monster buildPartial() {
          pl.marchuck.protobuffersexample.model.UserProtos.User.Monster result = new pl.marchuck.protobuffersexample.model.UserProtos.User.Monster(this);
          int from_bitField0_ = bitField0_;
          int to_bitField0_ = 0;
          if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
            to_bitField0_ |= 0x00000001;
          }
          result.id_ = id_;
          if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
            to_bitField0_ |= 0x00000002;
          }
          result.name_ = name_;
          if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
            to_bitField0_ |= 0x00000004;
          }
          result.type_ = type_;
          result.bitField0_ = to_bitField0_;
          onBuilt();
          return result;
        }

        public Builder clone() {
          return (Builder) super.clone();
        }
        public Builder setField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            Object value) {
          return (Builder) super.setField(field, value);
        }
        public Builder clearField(
            com.google.protobuf.Descriptors.FieldDescriptor field) {
          return (Builder) super.clearField(field);
        }
        public Builder clearOneof(
            com.google.protobuf.Descriptors.OneofDescriptor oneof) {
          return (Builder) super.clearOneof(oneof);
        }
        public Builder setRepeatedField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            int index, Object value) {
          return (Builder) super.setRepeatedField(field, index, value);
        }
        public Builder addRepeatedField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            Object value) {
          return (Builder) super.addRepeatedField(field, value);
        }
        public Builder mergeFrom(com.google.protobuf.Message other) {
          if (other instanceof pl.marchuck.protobuffersexample.model.UserProtos.User.Monster) {
            return mergeFrom((pl.marchuck.protobuffersexample.model.UserProtos.User.Monster)other);
          } else {
            super.mergeFrom(other);
            return this;
          }
        }

        public Builder mergeFrom(pl.marchuck.protobuffersexample.model.UserProtos.User.Monster other) {
          if (other == pl.marchuck.protobuffersexample.model.UserProtos.User.Monster.getDefaultInstance()) return this;
          if (other.hasId()) {
            setId(other.getId());
          }
          if (other.hasName()) {
            bitField0_ |= 0x00000002;
            name_ = other.name_;
            onChanged();
          }
          if (other.hasType()) {
            bitField0_ |= 0x00000004;
            type_ = other.type_;
            onChanged();
          }
          this.mergeUnknownFields(other.unknownFields);
          onChanged();
          return this;
        }

        public final boolean isInitialized() {
          if (!hasId()) {
            return false;
          }
          if (!hasName()) {
            return false;
          }
          return true;
        }

        public Builder mergeFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
          pl.marchuck.protobuffersexample.model.UserProtos.User.Monster parsedMessage = null;
          try {
            parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            parsedMessage = (pl.marchuck.protobuffersexample.model.UserProtos.User.Monster) e.getUnfinishedMessage();
            throw e.unwrapIOException();
          } finally {
            if (parsedMessage != null) {
              mergeFrom(parsedMessage);
            }
          }
          return this;
        }
        private int bitField0_;

        private int id_ ;
        /**
         * <code>required int32 id = 1;</code>
         */
        public boolean hasId() {
          return ((bitField0_ & 0x00000001) == 0x00000001);
        }
        /**
         * <code>required int32 id = 1;</code>
         */
        public int getId() {
          return id_;
        }
        /**
         * <code>required int32 id = 1;</code>
         */
        public Builder setId(int value) {
          bitField0_ |= 0x00000001;
          id_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>required int32 id = 1;</code>
         */
        public Builder clearId() {
          bitField0_ = (bitField0_ & ~0x00000001);
          id_ = 0;
          onChanged();
          return this;
        }

        private java.lang.Object name_ = "";
        /**
         * <code>required string name = 2;</code>
         */
        public boolean hasName() {
          return ((bitField0_ & 0x00000002) == 0x00000002);
        }
        /**
         * <code>required string name = 2;</code>
         */
        public java.lang.String getName() {
          java.lang.Object ref = name_;
          if (!(ref instanceof java.lang.String)) {
            com.google.protobuf.ByteString bs =
                (com.google.protobuf.ByteString) ref;
            java.lang.String s = bs.toStringUtf8();
            if (bs.isValidUtf8()) {
              name_ = s;
            }
            return s;
          } else {
            return (java.lang.String) ref;
          }
        }
        /**
         * <code>required string name = 2;</code>
         */
        public com.google.protobuf.ByteString
            getNameBytes() {
          java.lang.Object ref = name_;
          if (ref instanceof String) {
            com.google.protobuf.ByteString b = 
                com.google.protobuf.ByteString.copyFromUtf8(
                    (java.lang.String) ref);
            name_ = b;
            return b;
          } else {
            return (com.google.protobuf.ByteString) ref;
          }
        }
        /**
         * <code>required string name = 2;</code>
         */
        public Builder setName(
            java.lang.String value) {
          if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
          name_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>required string name = 2;</code>
         */
        public Builder clearName() {
          bitField0_ = (bitField0_ & ~0x00000002);
          name_ = getDefaultInstance().getName();
          onChanged();
          return this;
        }
        /**
         * <code>required string name = 2;</code>
         */
        public Builder setNameBytes(
            com.google.protobuf.ByteString value) {
          if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
          name_ = value;
          onChanged();
          return this;
        }

        private java.lang.Object type_ = "n/a";
        /**
         * <code>optional string type = 3 [default = "n/a"];</code>
         */
        public boolean hasType() {
          return ((bitField0_ & 0x00000004) == 0x00000004);
        }
        /**
         * <code>optional string type = 3 [default = "n/a"];</code>
         */
        public java.lang.String getType() {
          java.lang.Object ref = type_;
          if (!(ref instanceof java.lang.String)) {
            com.google.protobuf.ByteString bs =
                (com.google.protobuf.ByteString) ref;
            java.lang.String s = bs.toStringUtf8();
            if (bs.isValidUtf8()) {
              type_ = s;
            }
            return s;
          } else {
            return (java.lang.String) ref;
          }
        }
        /**
         * <code>optional string type = 3 [default = "n/a"];</code>
         */
        public com.google.protobuf.ByteString
            getTypeBytes() {
          java.lang.Object ref = type_;
          if (ref instanceof String) {
            com.google.protobuf.ByteString b = 
                com.google.protobuf.ByteString.copyFromUtf8(
                    (java.lang.String) ref);
            type_ = b;
            return b;
          } else {
            return (com.google.protobuf.ByteString) ref;
          }
        }
        /**
         * <code>optional string type = 3 [default = "n/a"];</code>
         */
        public Builder setType(
            java.lang.String value) {
          if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
          type_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>optional string type = 3 [default = "n/a"];</code>
         */
        public Builder clearType() {
          bitField0_ = (bitField0_ & ~0x00000004);
          type_ = getDefaultInstance().getType();
          onChanged();
          return this;
        }
        /**
         * <code>optional string type = 3 [default = "n/a"];</code>
         */
        public Builder setTypeBytes(
            com.google.protobuf.ByteString value) {
          if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
          type_ = value;
          onChanged();
          return this;
        }
        public final Builder setUnknownFields(
            final com.google.protobuf.UnknownFieldSet unknownFields) {
          return super.setUnknownFields(unknownFields);
        }

        public final Builder mergeUnknownFields(
            final com.google.protobuf.UnknownFieldSet unknownFields) {
          return super.mergeUnknownFields(unknownFields);
        }


        // @@protoc_insertion_point(builder_scope:pl.marchuck.protobuffersexample.User.Monster)
      }

      // @@protoc_insertion_point(class_scope:pl.marchuck.protobuffersexample.User.Monster)
      private static final pl.marchuck.protobuffersexample.model.UserProtos.User.Monster DEFAULT_INSTANCE;
      static {
        DEFAULT_INSTANCE = new pl.marchuck.protobuffersexample.model.UserProtos.User.Monster();
      }

      public static pl.marchuck.protobuffersexample.model.UserProtos.User.Monster getDefaultInstance() {
        return DEFAULT_INSTANCE;
      }

      @java.lang.Deprecated public static final com.google.protobuf.Parser<Monster>
          PARSER = new com.google.protobuf.AbstractParser<Monster>() {
        public Monster parsePartialFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
            return new Monster(input, extensionRegistry);
        }
      };

      public static com.google.protobuf.Parser<Monster> parser() {
        return PARSER;
      }

      @java.lang.Override
      public com.google.protobuf.Parser<Monster> getParserForType() {
        return PARSER;
      }

      public pl.marchuck.protobuffersexample.model.UserProtos.User.Monster getDefaultInstanceForType() {
        return DEFAULT_INSTANCE;
      }

    }

    private int bitField0_;
    public static final int ID_FIELD_NUMBER = 1;
    private int id_;
    /**
     * <code>required int32 id = 1;</code>
     */
    public boolean hasId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required int32 id = 1;</code>
     */
    public int getId() {
      return id_;
    }

    public static final int FIRSTNAME_FIELD_NUMBER = 2;
    private volatile java.lang.Object firstName_;
    /**
     * <code>required string firstName = 2;</code>
     */
    public boolean hasFirstName() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required string firstName = 2;</code>
     */
    public java.lang.String getFirstName() {
      java.lang.Object ref = firstName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          firstName_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string firstName = 2;</code>
     */
    public com.google.protobuf.ByteString
        getFirstNameBytes() {
      java.lang.Object ref = firstName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        firstName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int LASTNAME_FIELD_NUMBER = 3;
    private volatile java.lang.Object lastName_;
    /**
     * <code>required string lastName = 3;</code>
     */
    public boolean hasLastName() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>required string lastName = 3;</code>
     */
    public java.lang.String getLastName() {
      java.lang.Object ref = lastName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          lastName_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string lastName = 3;</code>
     */
    public com.google.protobuf.ByteString
        getLastNameBytes() {
      java.lang.Object ref = lastName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        lastName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int LEVEL_FIELD_NUMBER = 4;
    private int level_;
    /**
     * <code>optional int32 level = 4 [default = 0];</code>
     */
    public boolean hasLevel() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>optional int32 level = 4 [default = 0];</code>
     */
    public int getLevel() {
      return level_;
    }

    public static final int MONSTERS_FIELD_NUMBER = 5;
    private java.util.List<pl.marchuck.protobuffersexample.model.UserProtos.User.Monster> monsters_;
    /**
     * <code>repeated .pl.marchuck.protobuffersexample.User.Monster monsters = 5;</code>
     */
    public java.util.List<pl.marchuck.protobuffersexample.model.UserProtos.User.Monster> getMonstersList() {
      return monsters_;
    }
    /**
     * <code>repeated .pl.marchuck.protobuffersexample.User.Monster monsters = 5;</code>
     */
    public java.util.List<? extends pl.marchuck.protobuffersexample.model.UserProtos.User.MonsterOrBuilder> 
        getMonstersOrBuilderList() {
      return monsters_;
    }
    /**
     * <code>repeated .pl.marchuck.protobuffersexample.User.Monster monsters = 5;</code>
     */
    public int getMonstersCount() {
      return monsters_.size();
    }
    /**
     * <code>repeated .pl.marchuck.protobuffersexample.User.Monster monsters = 5;</code>
     */
    public pl.marchuck.protobuffersexample.model.UserProtos.User.Monster getMonsters(int index) {
      return monsters_.get(index);
    }
    /**
     * <code>repeated .pl.marchuck.protobuffersexample.User.Monster monsters = 5;</code>
     */
    public pl.marchuck.protobuffersexample.model.UserProtos.User.MonsterOrBuilder getMonstersOrBuilder(
        int index) {
      return monsters_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasFirstName()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasLastName()) {
        memoizedIsInitialized = 0;
        return false;
      }
      for (int i = 0; i < getMonstersCount(); i++) {
        if (!getMonsters(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, id_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, firstName_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, lastName_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeInt32(4, level_);
      }
      for (int i = 0; i < monsters_.size(); i++) {
        output.writeMessage(5, monsters_.get(i));
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, id_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, firstName_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, lastName_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(4, level_);
      }
      for (int i = 0; i < monsters_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(5, monsters_.get(i));
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof pl.marchuck.protobuffersexample.model.UserProtos.User)) {
        return super.equals(obj);
      }
      pl.marchuck.protobuffersexample.model.UserProtos.User other = (pl.marchuck.protobuffersexample.model.UserProtos.User) obj;

      boolean result = true;
      result = result && (hasId() == other.hasId());
      if (hasId()) {
        result = result && (getId()
            == other.getId());
      }
      result = result && (hasFirstName() == other.hasFirstName());
      if (hasFirstName()) {
        result = result && getFirstName()
            .equals(other.getFirstName());
      }
      result = result && (hasLastName() == other.hasLastName());
      if (hasLastName()) {
        result = result && getLastName()
            .equals(other.getLastName());
      }
      result = result && (hasLevel() == other.hasLevel());
      if (hasLevel()) {
        result = result && (getLevel()
            == other.getLevel());
      }
      result = result && getMonstersList()
          .equals(other.getMonstersList());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      if (hasId()) {
        hash = (37 * hash) + ID_FIELD_NUMBER;
        hash = (53 * hash) + getId();
      }
      if (hasFirstName()) {
        hash = (37 * hash) + FIRSTNAME_FIELD_NUMBER;
        hash = (53 * hash) + getFirstName().hashCode();
      }
      if (hasLastName()) {
        hash = (37 * hash) + LASTNAME_FIELD_NUMBER;
        hash = (53 * hash) + getLastName().hashCode();
      }
      if (hasLevel()) {
        hash = (37 * hash) + LEVEL_FIELD_NUMBER;
        hash = (53 * hash) + getLevel();
      }
      if (getMonstersCount() > 0) {
        hash = (37 * hash) + MONSTERS_FIELD_NUMBER;
        hash = (53 * hash) + getMonstersList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static pl.marchuck.protobuffersexample.model.UserProtos.User parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static pl.marchuck.protobuffersexample.model.UserProtos.User parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static pl.marchuck.protobuffersexample.model.UserProtos.User parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static pl.marchuck.protobuffersexample.model.UserProtos.User parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static pl.marchuck.protobuffersexample.model.UserProtos.User parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static pl.marchuck.protobuffersexample.model.UserProtos.User parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static pl.marchuck.protobuffersexample.model.UserProtos.User parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static pl.marchuck.protobuffersexample.model.UserProtos.User parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static pl.marchuck.protobuffersexample.model.UserProtos.User parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static pl.marchuck.protobuffersexample.model.UserProtos.User parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(pl.marchuck.protobuffersexample.model.UserProtos.User prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code pl.marchuck.protobuffersexample.User}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:pl.marchuck.protobuffersexample.User)
        pl.marchuck.protobuffersexample.model.UserProtos.UserOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return pl.marchuck.protobuffersexample.model.UserProtos.internal_static_pl_marchuck_protobuffersexample_User_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return pl.marchuck.protobuffersexample.model.UserProtos.internal_static_pl_marchuck_protobuffersexample_User_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                pl.marchuck.protobuffersexample.model.UserProtos.User.class, pl.marchuck.protobuffersexample.model.UserProtos.User.Builder.class);
      }

      // Construct using pl.marchuck.protobuffersexample.model.UserProtos.User.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getMonstersFieldBuilder();
        }
      }
      public Builder clear() {
        super.clear();
        id_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        firstName_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        lastName_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        level_ = 0;
        bitField0_ = (bitField0_ & ~0x00000008);
        if (monstersBuilder_ == null) {
          monsters_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000010);
        } else {
          monstersBuilder_.clear();
        }
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return pl.marchuck.protobuffersexample.model.UserProtos.internal_static_pl_marchuck_protobuffersexample_User_descriptor;
      }

      public pl.marchuck.protobuffersexample.model.UserProtos.User getDefaultInstanceForType() {
        return pl.marchuck.protobuffersexample.model.UserProtos.User.getDefaultInstance();
      }

      public pl.marchuck.protobuffersexample.model.UserProtos.User build() {
        pl.marchuck.protobuffersexample.model.UserProtos.User result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public pl.marchuck.protobuffersexample.model.UserProtos.User buildPartial() {
        pl.marchuck.protobuffersexample.model.UserProtos.User result = new pl.marchuck.protobuffersexample.model.UserProtos.User(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.id_ = id_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.firstName_ = firstName_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.lastName_ = lastName_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.level_ = level_;
        if (monstersBuilder_ == null) {
          if (((bitField0_ & 0x00000010) == 0x00000010)) {
            monsters_ = java.util.Collections.unmodifiableList(monsters_);
            bitField0_ = (bitField0_ & ~0x00000010);
          }
          result.monsters_ = monsters_;
        } else {
          result.monsters_ = monstersBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof pl.marchuck.protobuffersexample.model.UserProtos.User) {
          return mergeFrom((pl.marchuck.protobuffersexample.model.UserProtos.User)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(pl.marchuck.protobuffersexample.model.UserProtos.User other) {
        if (other == pl.marchuck.protobuffersexample.model.UserProtos.User.getDefaultInstance()) return this;
        if (other.hasId()) {
          setId(other.getId());
        }
        if (other.hasFirstName()) {
          bitField0_ |= 0x00000002;
          firstName_ = other.firstName_;
          onChanged();
        }
        if (other.hasLastName()) {
          bitField0_ |= 0x00000004;
          lastName_ = other.lastName_;
          onChanged();
        }
        if (other.hasLevel()) {
          setLevel(other.getLevel());
        }
        if (monstersBuilder_ == null) {
          if (!other.monsters_.isEmpty()) {
            if (monsters_.isEmpty()) {
              monsters_ = other.monsters_;
              bitField0_ = (bitField0_ & ~0x00000010);
            } else {
              ensureMonstersIsMutable();
              monsters_.addAll(other.monsters_);
            }
            onChanged();
          }
        } else {
          if (!other.monsters_.isEmpty()) {
            if (monstersBuilder_.isEmpty()) {
              monstersBuilder_.dispose();
              monstersBuilder_ = null;
              monsters_ = other.monsters_;
              bitField0_ = (bitField0_ & ~0x00000010);
              monstersBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getMonstersFieldBuilder() : null;
            } else {
              monstersBuilder_.addAllMessages(other.monsters_);
            }
          }
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        if (!hasId()) {
          return false;
        }
        if (!hasFirstName()) {
          return false;
        }
        if (!hasLastName()) {
          return false;
        }
        for (int i = 0; i < getMonstersCount(); i++) {
          if (!getMonsters(i).isInitialized()) {
            return false;
          }
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        pl.marchuck.protobuffersexample.model.UserProtos.User parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (pl.marchuck.protobuffersexample.model.UserProtos.User) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int id_ ;
      /**
       * <code>required int32 id = 1;</code>
       */
      public boolean hasId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required int32 id = 1;</code>
       */
      public int getId() {
        return id_;
      }
      /**
       * <code>required int32 id = 1;</code>
       */
      public Builder setId(int value) {
        bitField0_ |= 0x00000001;
        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 id = 1;</code>
       */
      public Builder clearId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        id_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object firstName_ = "";
      /**
       * <code>required string firstName = 2;</code>
       */
      public boolean hasFirstName() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required string firstName = 2;</code>
       */
      public java.lang.String getFirstName() {
        java.lang.Object ref = firstName_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            firstName_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string firstName = 2;</code>
       */
      public com.google.protobuf.ByteString
          getFirstNameBytes() {
        java.lang.Object ref = firstName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          firstName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string firstName = 2;</code>
       */
      public Builder setFirstName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        firstName_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string firstName = 2;</code>
       */
      public Builder clearFirstName() {
        bitField0_ = (bitField0_ & ~0x00000002);
        firstName_ = getDefaultInstance().getFirstName();
        onChanged();
        return this;
      }
      /**
       * <code>required string firstName = 2;</code>
       */
      public Builder setFirstNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        firstName_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object lastName_ = "";
      /**
       * <code>required string lastName = 3;</code>
       */
      public boolean hasLastName() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>required string lastName = 3;</code>
       */
      public java.lang.String getLastName() {
        java.lang.Object ref = lastName_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            lastName_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string lastName = 3;</code>
       */
      public com.google.protobuf.ByteString
          getLastNameBytes() {
        java.lang.Object ref = lastName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          lastName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string lastName = 3;</code>
       */
      public Builder setLastName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        lastName_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string lastName = 3;</code>
       */
      public Builder clearLastName() {
        bitField0_ = (bitField0_ & ~0x00000004);
        lastName_ = getDefaultInstance().getLastName();
        onChanged();
        return this;
      }
      /**
       * <code>required string lastName = 3;</code>
       */
      public Builder setLastNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        lastName_ = value;
        onChanged();
        return this;
      }

      private int level_ ;
      /**
       * <code>optional int32 level = 4 [default = 0];</code>
       */
      public boolean hasLevel() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>optional int32 level = 4 [default = 0];</code>
       */
      public int getLevel() {
        return level_;
      }
      /**
       * <code>optional int32 level = 4 [default = 0];</code>
       */
      public Builder setLevel(int value) {
        bitField0_ |= 0x00000008;
        level_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 level = 4 [default = 0];</code>
       */
      public Builder clearLevel() {
        bitField0_ = (bitField0_ & ~0x00000008);
        level_ = 0;
        onChanged();
        return this;
      }

      private java.util.List<pl.marchuck.protobuffersexample.model.UserProtos.User.Monster> monsters_ =
        java.util.Collections.emptyList();
      private void ensureMonstersIsMutable() {
        if (!((bitField0_ & 0x00000010) == 0x00000010)) {
          monsters_ = new java.util.ArrayList<pl.marchuck.protobuffersexample.model.UserProtos.User.Monster>(monsters_);
          bitField0_ |= 0x00000010;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          pl.marchuck.protobuffersexample.model.UserProtos.User.Monster, pl.marchuck.protobuffersexample.model.UserProtos.User.Monster.Builder, pl.marchuck.protobuffersexample.model.UserProtos.User.MonsterOrBuilder> monstersBuilder_;

      /**
       * <code>repeated .pl.marchuck.protobuffersexample.User.Monster monsters = 5;</code>
       */
      public java.util.List<pl.marchuck.protobuffersexample.model.UserProtos.User.Monster> getMonstersList() {
        if (monstersBuilder_ == null) {
          return java.util.Collections.unmodifiableList(monsters_);
        } else {
          return monstersBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .pl.marchuck.protobuffersexample.User.Monster monsters = 5;</code>
       */
      public int getMonstersCount() {
        if (monstersBuilder_ == null) {
          return monsters_.size();
        } else {
          return monstersBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .pl.marchuck.protobuffersexample.User.Monster monsters = 5;</code>
       */
      public pl.marchuck.protobuffersexample.model.UserProtos.User.Monster getMonsters(int index) {
        if (monstersBuilder_ == null) {
          return monsters_.get(index);
        } else {
          return monstersBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .pl.marchuck.protobuffersexample.User.Monster monsters = 5;</code>
       */
      public Builder setMonsters(
          int index, pl.marchuck.protobuffersexample.model.UserProtos.User.Monster value) {
        if (monstersBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureMonstersIsMutable();
          monsters_.set(index, value);
          onChanged();
        } else {
          monstersBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .pl.marchuck.protobuffersexample.User.Monster monsters = 5;</code>
       */
      public Builder setMonsters(
          int index, pl.marchuck.protobuffersexample.model.UserProtos.User.Monster.Builder builderForValue) {
        if (monstersBuilder_ == null) {
          ensureMonstersIsMutable();
          monsters_.set(index, builderForValue.build());
          onChanged();
        } else {
          monstersBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .pl.marchuck.protobuffersexample.User.Monster monsters = 5;</code>
       */
      public Builder addMonsters(pl.marchuck.protobuffersexample.model.UserProtos.User.Monster value) {
        if (monstersBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureMonstersIsMutable();
          monsters_.add(value);
          onChanged();
        } else {
          monstersBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .pl.marchuck.protobuffersexample.User.Monster monsters = 5;</code>
       */
      public Builder addMonsters(
          int index, pl.marchuck.protobuffersexample.model.UserProtos.User.Monster value) {
        if (monstersBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureMonstersIsMutable();
          monsters_.add(index, value);
          onChanged();
        } else {
          monstersBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .pl.marchuck.protobuffersexample.User.Monster monsters = 5;</code>
       */
      public Builder addMonsters(
          pl.marchuck.protobuffersexample.model.UserProtos.User.Monster.Builder builderForValue) {
        if (monstersBuilder_ == null) {
          ensureMonstersIsMutable();
          monsters_.add(builderForValue.build());
          onChanged();
        } else {
          monstersBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .pl.marchuck.protobuffersexample.User.Monster monsters = 5;</code>
       */
      public Builder addMonsters(
          int index, pl.marchuck.protobuffersexample.model.UserProtos.User.Monster.Builder builderForValue) {
        if (monstersBuilder_ == null) {
          ensureMonstersIsMutable();
          monsters_.add(index, builderForValue.build());
          onChanged();
        } else {
          monstersBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .pl.marchuck.protobuffersexample.User.Monster monsters = 5;</code>
       */
      public Builder addAllMonsters(
          java.lang.Iterable<? extends pl.marchuck.protobuffersexample.model.UserProtos.User.Monster> values) {
        if (monstersBuilder_ == null) {
          ensureMonstersIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, monsters_);
          onChanged();
        } else {
          monstersBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .pl.marchuck.protobuffersexample.User.Monster monsters = 5;</code>
       */
      public Builder clearMonsters() {
        if (monstersBuilder_ == null) {
          monsters_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000010);
          onChanged();
        } else {
          monstersBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .pl.marchuck.protobuffersexample.User.Monster monsters = 5;</code>
       */
      public Builder removeMonsters(int index) {
        if (monstersBuilder_ == null) {
          ensureMonstersIsMutable();
          monsters_.remove(index);
          onChanged();
        } else {
          monstersBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .pl.marchuck.protobuffersexample.User.Monster monsters = 5;</code>
       */
      public pl.marchuck.protobuffersexample.model.UserProtos.User.Monster.Builder getMonstersBuilder(
          int index) {
        return getMonstersFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .pl.marchuck.protobuffersexample.User.Monster monsters = 5;</code>
       */
      public pl.marchuck.protobuffersexample.model.UserProtos.User.MonsterOrBuilder getMonstersOrBuilder(
          int index) {
        if (monstersBuilder_ == null) {
          return monsters_.get(index);  } else {
          return monstersBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .pl.marchuck.protobuffersexample.User.Monster monsters = 5;</code>
       */
      public java.util.List<? extends pl.marchuck.protobuffersexample.model.UserProtos.User.MonsterOrBuilder> 
           getMonstersOrBuilderList() {
        if (monstersBuilder_ != null) {
          return monstersBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(monsters_);
        }
      }
      /**
       * <code>repeated .pl.marchuck.protobuffersexample.User.Monster monsters = 5;</code>
       */
      public pl.marchuck.protobuffersexample.model.UserProtos.User.Monster.Builder addMonstersBuilder() {
        return getMonstersFieldBuilder().addBuilder(
            pl.marchuck.protobuffersexample.model.UserProtos.User.Monster.getDefaultInstance());
      }
      /**
       * <code>repeated .pl.marchuck.protobuffersexample.User.Monster monsters = 5;</code>
       */
      public pl.marchuck.protobuffersexample.model.UserProtos.User.Monster.Builder addMonstersBuilder(
          int index) {
        return getMonstersFieldBuilder().addBuilder(
            index, pl.marchuck.protobuffersexample.model.UserProtos.User.Monster.getDefaultInstance());
      }
      /**
       * <code>repeated .pl.marchuck.protobuffersexample.User.Monster monsters = 5;</code>
       */
      public java.util.List<pl.marchuck.protobuffersexample.model.UserProtos.User.Monster.Builder> 
           getMonstersBuilderList() {
        return getMonstersFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          pl.marchuck.protobuffersexample.model.UserProtos.User.Monster, pl.marchuck.protobuffersexample.model.UserProtos.User.Monster.Builder, pl.marchuck.protobuffersexample.model.UserProtos.User.MonsterOrBuilder> 
          getMonstersFieldBuilder() {
        if (monstersBuilder_ == null) {
          monstersBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              pl.marchuck.protobuffersexample.model.UserProtos.User.Monster, pl.marchuck.protobuffersexample.model.UserProtos.User.Monster.Builder, pl.marchuck.protobuffersexample.model.UserProtos.User.MonsterOrBuilder>(
                  monsters_,
                  ((bitField0_ & 0x00000010) == 0x00000010),
                  getParentForChildren(),
                  isClean());
          monsters_ = null;
        }
        return monstersBuilder_;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:pl.marchuck.protobuffersexample.User)
    }

    // @@protoc_insertion_point(class_scope:pl.marchuck.protobuffersexample.User)
    private static final pl.marchuck.protobuffersexample.model.UserProtos.User DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new pl.marchuck.protobuffersexample.model.UserProtos.User();
    }

    public static pl.marchuck.protobuffersexample.model.UserProtos.User getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<User>
        PARSER = new com.google.protobuf.AbstractParser<User>() {
      public User parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new User(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<User> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<User> getParserForType() {
      return PARSER;
    }

    public pl.marchuck.protobuffersexample.model.UserProtos.User getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_pl_marchuck_protobuffersexample_User_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_pl_marchuck_protobuffersexample_User_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_pl_marchuck_protobuffersexample_User_Monster_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_pl_marchuck_protobuffersexample_User_Monster_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\nUser.proto\022\037pl.marchuck.protobuffersex" +
      "ample\"\302\001\n\004User\022\n\n\002id\030\001 \002(\005\022\021\n\tfirstName\030" +
      "\002 \002(\t\022\020\n\010lastName\030\003 \002(\t\022\020\n\005level\030\004 \001(\005:\001" +
      "0\022?\n\010monsters\030\005 \003(\0132-.pl.marchuck.protob" +
      "uffersexample.User.Monster\0326\n\007Monster\022\n\n" +
      "\002id\030\001 \002(\005\022\014\n\004name\030\002 \002(\t\022\021\n\004type\030\003 \001(\t:\003n" +
      "/aB3\n%pl.marchuck.protobuffersexample.mo" +
      "delB\nUserProtos"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_pl_marchuck_protobuffersexample_User_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_pl_marchuck_protobuffersexample_User_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_pl_marchuck_protobuffersexample_User_descriptor,
        new java.lang.String[] { "Id", "FirstName", "LastName", "Level", "Monsters", });
    internal_static_pl_marchuck_protobuffersexample_User_Monster_descriptor =
      internal_static_pl_marchuck_protobuffersexample_User_descriptor.getNestedTypes().get(0);
    internal_static_pl_marchuck_protobuffersexample_User_Monster_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_pl_marchuck_protobuffersexample_User_Monster_descriptor,
        new java.lang.String[] { "Id", "Name", "Type", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
